services:
  nestjs:
    build: .
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/home/node/app
  db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_DATABASE: nestjs
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306